### PR TITLE
Reorganize the library into submodules.

### PR DESCRIPTION
**Pull request by atheriel**
Cross-repo commit splicing incoming...

This is the first part of my [PR #90 on hematite_server](https://github.com/PistonDevelopers/hematite_server/pull/90), ported to this repo instead using `git cherry-pick`.

It breaks the single library file up into a series of manageable submodules (in preparation for adding several new ones). Functionality is unchanged.

### CODE REVIEW

**Comment by fenhl** [comment]
By convention, the types should be called `Error` instead of `NbtError` etc.

**Comment by atheriel** [comment]
I strongly dislike this trend, actually. It makes reading documentation (which doesn't show full paths) more difficult as well. A library prefix makes much more sense to me.

**Comment by eddyb** [comment]
@atheriel blame the compiler, which doesn't have facilities for determining the shortest unambiguous path to an item.

**Comment by fenhl** [comment]
I think the convention makes sense, since namespacing is already provided by the module name. The documentation not showing paths can be a minor annoyance, but the tooltips are very helpful.

**Comment by atheriel** [comment]
OK, renamed. For the record, I do thing this is a bad idea (for the Rust community generally), but there's no doubt it's the current convention. We can always change it later.

**Comment by atheriel** [comment]
@fenhl Unless there are any big issues remaining here, I'm going to merge this so I can get back to the serialization stuff. No use leaving it to languish.

**Comment by fenhl** [comment]
@atheriel Oh, by “etc.” I meant `NbtBlob` should be `Blob` (or maybe `Nbt`) and `NbtValue` should be `Value`.

**Comment by atheriel** [comment]
Oh, I have no issues with new names for those -- feel free. I'm hoping `NbtBlob` will disappear soon, though.

**Pull request merged**
