### PR TITLE
Add support for TAG_LongArray

### PR DESCRIPTION
**Pull request by williewillus**
TAG_LongArray (tag id 12) was introduced somewhere around 1.9/1.10 and ~~is used in the world format of newer versions~~ will be used in the world format starting from 1.13 - add support for it.

I didn't touch the serde implementation as I'm not familiar enough with serde, so additional changes might be needed there.

### CODE REVIEW

**Comment by atheriel** [comment]
This is great, thank you! Have you done any testing to see that it works?

**Comment by atheriel** [comment]
Also, don't worry too much about the serde code. It's not that hard to add if you know exactly where to look, but that crate is frozen for the moment since it needs to be ported to the post-1.0 API.

**Comment by williewillus** [comment]
Added a brief test case for all three array types, the NBT file in question was generated using the Java game code (via MCP/Forge)

**Comment by atheriel** [comment]
Looks good to me.

**Pull request merged**
